name: Destroy Infrastructure (THIS DELETES YOUR ENV MAKE SURE YOU WANT THIS !!! )
run-name: Destroy Infrastructure  ${{ inputs.Environment }}

on:
  workflow_dispatch:
    inputs:
      Environment:
        description: 'Environment'
        type: environment
        required: true
      AppId:
        type: choice
        description: 'ApplicationId'
        required: true
        options: 
           - a

permissions:
  id-token: write
  contents: write

jobs:

  resource-group-creation:
    runs-on: ubuntu-latest
    environment: ${{ inputs.Environment }}

    steps:
    # Checkout code
    - uses: actions/checkout@v3
    # Set Env variables for the root first then override any environment specific 
    - name: Set the value
      id: step_one
      run: |
            cat env/.env >>${GITHUB_ENV} 
            cat env/${{ inputs.Environment }}/${{ inputs.AppId }}/.env >>${GITHUB_ENV}

    - name: read the value
      id: step_2
      run: |
              echo ${{ env.APPLICATION_NAME }}
              